version: '3'

services:
  server:
    build: .
    restart: always
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 3000:3000
    command: npm run dev
    depends_on:
      - db

  db:
    image: aashreys/mongo-auth:latest
    command: mongod --port 27018
    ports:
      - 27018:27018