version: '3'

services:
  server:
    container_name: desafio
    build: '.'
    volumes:
      - ./:/node-app
      - ./node_modules:/node-app/node_modules
    environment:
      NODE_ENV: development
    depends_on:
      - db
    links:
      - db
    ports:
      - '3000:3000'

  db:
    image: 'mongo'
    container_name: desafiodb
    command: mongod --port 27018
    ports:
      - '27018:27018'
    volumes:
      - ./data/db:/data/db